spring:
  application:
    name : "app_factor-ecommerce"
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  ###############################################################################################
  #                     DATASOURCE
  ###############################################################################################
  datasource:
    url: ${DB_URL}  # ${jdbc:mysql://mysql-container:3306/db_ecommerce}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    name :  f-ecommerce
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update

