spring:
  application:
    name : "factor-ecommerce"
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  ###############################################################################################
  #                     DATASOURCE
  ###############################################################################################
  datasource:
  url: jdbc:mysql://mysql-container:3306/db_name
  username: your_username
  password: your_password
  jpa:
  database-platform: org.hibernate.dialect.MySQL5Dialect
  hibernate:
  ddl-auto: update

